---
# tasks file for ansible-role-nginx
- name: Install Nginx
  yum:
    name: nginx
    state: latest
    update_cache: true
- name: Create phpMyAdmin nginx file
  blockinfile:
    path: /etc/nginx/conf.d/phpMyAdmin.conf
    create: yes
    block: |
      server {
      listen 8080;
      server_name 131.154.161.25;
      root /var/www;
      location /phpMyAdmin {
          root /usr/share/;
          index index.php;

          #auth_basic "phpMyAdmin Login";
          #auth_basic_user_file /etc/nginx/.pma_pass;

          location ~\.php$ {
              try_files $uri =404;
              fastcgi_pass 127.0.0.1:9000;
              fastcgi_index index.php;
              fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
              include /etc/nginx/fastcgi_params;
              }

          location ~* ^/phpmyadmin/(.+\.(jpg|jpeg|gif|css|png|js|ico|html|xml|txt))$ {
           root /usr/share/;
              }
          }

          location /phpmyadmin {
          rewrite ^/* /phpMyAdmin last;
          }
      }
  notify: restart nginx
- name: Change default port in nginx.conf
  replace:
    path: /etc/nginx/nginx.conf
    regexp: '{{item.From}}'
    replace: '{{item.To}}'
  with_items:
    - { From: '^        listen       \[\:\:\]\:(.*)\;$', To: "        listen      	[::]:{{ nginx_default_port }};"}
    - { From: '^        listen       (.*)\;$', To: "        listen       {{ nginx_default_port }};"}
  notify: restart nginx
- name: ensure nginx is running (and enabled)
  service:
    name: nginx
    state: started
    enabled: yes
